---
- name: Hardening de servidores
  hosts: linux
  become: true
  user: sysadmin

  tasks:

  - name: Configuro opciones de seguridad de SSH
    ansible.builtin.lineinfile: 
      path: /etc/ssh/ssh_config
      regexp: '^#PermitRootLogin'
      line: PermitRootLogin no
    notify: Reinicio de servicio ssh 
    register: results_sshd

  - name: Ver resultado de tarea anterior
    ansible.builtin.debug:
      var: results_sshd

  handlers:

  - name: Reinicio de servicio ssh
    ansible.builtin.systemd.service:
      name: "{{ ssh_service }}"
      state: restarted 
